ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQM2iiiW+Wn/NsCWONu7l62TANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwMjA0MDY1NTUwWhcNMzUw
  MjAyMDY1NTUwWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDvDWldhDGxLzop6ek0Ph97U5iYRExrWK0
  NzDQDzWRk6u+Ls21UkT3BFS71xxNL/RAgMoEIM/LE4cpqbfh5Txs7iBxrr/dBKS3
  QVM5v/J/iuaq8S+b+TehJ2lzk49S4xR8n4b3FBaZidele68OzfWbhyAQKLS7Yuzn
  KyNwkVVvR2sdsAVFSJLkTm3Ai2FWtmz1n8A7dtZ3G4AAMnEivENfPq+FhMa8eZq3
  WOhx/33nLqWEVsAzay21kLDflC6DtUNPIClzdP64XncHIFm4pN7IN51irvPHElqp
  yRR1P9two3XEZCceS4j8uI5J+FG2uYF0aL8ao1/c+0KTvDKz0UfXAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT4I2HPQEXDM2/9+kz2XIhC+DGg
  EDAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEANw/bgeZpCVl/gzLN3aQSl8kLszLTv+T9YyBTaDnoIzWM
  JyuXLlMBj3jXfe5f3g1LMw6UwpdXZYWMDEPtPz05C75D0vwOaw6om/HqAhV9qhvs
  aiQ1DfEc54tWwOFoS7SBRnUXkfXGDbL4h30DZdXF++bil+0L1tVazspAbIBGLEGV
  qnMwgKS+lnQlAo9Y8926/8JICf6ZpCvrmwbV/iBYS/UTHg+ymvGWbOyhs4Tv120F
  lva7cCcI442yfYLtlDWAaELokdYcS2YbR/Gr1/7cj3tkxGqHR5S+BKHFKwOsNkS6
  S89mVcVlcEYC4U6T2Lr+NGadIB4Dz0rrkmnl9+ACXA==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPjCCAiagAwIBAgIRANrWkpFtGrH8vgSlHICbSvMwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDIxMDA1MTMyN1oXDTI2
  MDIxMDA1MTMyN1owJzEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMQ4wDAYDVQQDEwVh
  ZG1pbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOehPRC5ck5bGafo
  C+LgNv/n2hYh4Do24SwlcdWhd+17+1dw2KgMwN4bt3aZ8K1v8mn89K5qAGtMKd7+
  jh6w9FL0j6MeNj7SnBWuVpDHuXRHv/r+yuZuY0BQ0g67tgGTYNABbEukjtpISYz7
  RsZwJdKfPSFNSK7B/KSwPYwFJO+pADzKvGV6vnYdtADIxDaPS89JohkC7WYq4/BW
  /Olkf+BEpikb8JPvD9VEQQ/I7znO/669DvyJtKxTWXpTvp3eYDMYqekG+NX41XCD
  PRtiIdSpTGMnKBDFAe0oP/sbsuD8aMx6z1jdqPx10kTLVaE+mbXiliF6rKe9XFj3
  rp5urhECAwEAAaNyMHAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
  BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFPgjYc9ARcMz
  b/36TPZciEL4MaAQMBAGA1UdEQQJMAeCBWFkbWluMA0GCSqGSIb3DQEBCwUAA4IB
  AQC5orCzMqETqwXuQracK1c8wIGSaJsbTp39QcmOyRbnpEpMsYIEm1IQW/dNx1Nd
  5cJPSBB/CsJrTFWN3PBFAA9qYLkiu0foYyf9313ftR2VJebixF0Y5bG9D81VDMvv
  U1IbBF3e0npsypTOWJ4TtGFlI1z/7vkcRqQ59ppupQkI6eYrAnFAGjIChueREn+o
  bRbLDFYhPPyKkhRkP7WRUJnIONTkwn3PcO7QmMFf7KMYOMMM2E/ff6ZHhDiuh0ur
  +/VmMe1hkQU70J0BGb/1+OEw4tRnus7uz/VfT7bmgO92swDBrmV2dPAiZtb/F9Y8
  c8cX/GvNcqAWOLRT01OXQ7P0
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEA56E9ELlyTlsZp+gL4uA2/+faFiHgOjbhLCVx1aF37Xv7V3DY
  qAzA3hu3dpnwrW/yafz0rmoAa0wp3v6OHrD0UvSPox42PtKcFa5WkMe5dEe/+v7K
  5m5jQFDSDru2AZNg0AFsS6SO2khJjPtGxnAl0p89IU1IrsH8pLA9jAUk76kAPMq8
  ZXq+dh20AMjENo9Lz0miGQLtZirj8Fb86WR/4ESmKRvwk+8P1URBD8jvOc7/rr0O
  /Im0rFNZelO+nd5gMxip6Qb41fjVcIM9G2Ih1KlMYycoEMUB7Sg/+xuy4PxozHrP
  WN2o/HXSRMtVoT6ZteKWIXqsp71cWPeunm6uEQIDAQABAoIBAApzdvrjMyof6Cdw
  S+D/ttuTDX8EJkbaJQzF374A3BVmC7AlUlE6yhT7cSqzxW096NUpaazY8Y3l0NnT
  6HuwBkYb7MMyYMYy4IIF7Lf5mv+JITtk9aiyAF5thxzNEWg+yxZ3ifhbw2pL6q2m
  xMm9U6eOMcbn4sinzgtsPEquDL2Xb4ann/CoRr6meI8thtBxuxQ0m6z03QOWW88L
  tPwH79qXyBqySqSeGlMRS/RzLii63mOAtZfgMbT6KpyBNkugoEnx7UIKCqLHcqCG
  c78TfLlAwOP+IRVSmOivYLG+r8Mlk4E7ciFn1kSA8Un9LweNuStbnzK+aXl14Y91
  VWq55gECgYEA9X7Pd0eOlD3WqrC3k4QonP+VoNVle/iAYE2cOLEaa0kxE9/Y4pMK
  u2/HKYuc2MJocEfORZOAeruVyiV9vJSNmhS0Jk4Dlg4F4avnlBhIgncsjqCKmnqm
  4gofz+mLtZvOyWKe9KPwHu/ASA+rciE6c3cOiQMBb3WzxND5sil/b/ECgYEA8YqL
  Gtgf/PKnM8O5Du95rxOavE1Z6vCIt0kUoL9D8ZF7DclFXOFmoP/4SPjc0dIgxWRp
  4xJ67zZFQeA8WyKaHAmYnTwD7vXTfZi1Qz3dH90kmKRPEAO/kMFUrUQWvdNj71aO
  mUT9f0jyVTriVTHcb5EXh++rsWOdHNN+eR5VQCECgYA0fNRmsEnvr/kBrZ7ST2NP
  jeWz6Ww1QUBRVsab6GG5poBzu1xntQCKaq+uVkdGoOord27GuW6yzwCLo9BqTWip
  FNwfhHaH0p+3TEXLCBYYrto79F8uACNGGNwMW+afAZ0Iuak6rQJd2uzFe3QwhqI0
  pbPZ32ajKgsxfWylhvHUQQKBgCglm/tpQt/bQTlUZdT6ruIPwx9bR//J3R+B0SDq
  yZNEWAyxkIrgmBtYkF8opiNl5raIeyUX9EEAZ0CM0dtgA/d3DNvNluXIDFAK6s3z
  YWajbirE3LNPvC6GQ9nMwG7qzOiCHY+SLQRUDptl/yqj7/zHQ/7/Mi143itlZ9cf
  2JGhAoGAE48V5sJzLYrwta6N2YerKZU9WmMietaCNymmHAdTLgsU77NKvLWnZHox
  ED3qgwxR+rgLqE/Ke8ToBdlsF3AKvtZHqU3BjHKnd9PRHuqe7p+iQu4nnorSwaoW
  gnBS9KUmG8ahHsxk9x0GMXO4y/FZgccFc1Pi17T7AtXuOaqvXrQ=
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.45.154.74:8001
name: admin
