# Generated by Django 5.1.1 on 2024-10-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='devices',
        #     name='boot_time',
        #     field=models.IntegerField(),
        # ),
    ]
