# Generated by Django 5.1.1 on 2024-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0002_alter_devices_boot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='boot_time',
            field=models.DateTimeField(),
        ),
    ]
