# Generated by Django 5.1.1 on 2024-10-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0003_alter_devices_boot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
