# Generated by Django 5.1.1 on 2024-11-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0009_devicehost_status_devicesclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehost',
            name='uptime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
