# Generated by Django 5.1.1 on 2024-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0013_remove_devicehost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesclient',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
    ]
