# Generated by Django 5.1.1 on 2024-11-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0014_alter_devicesclient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehost',
            name='procs',
        ),
    ]
