# Generated by Django 5.1.1 on 2025-01-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0015_remove_devicehost_procs'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryVQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('query_vql', models.TextField()),
            ],
        ),
    ]
