# Generated by Django 5.1.1 on 2025-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0016_queryvql'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesclient',
            name='first_seen_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='fqdn',
            field=models.CharField(default='t', max_length=255),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='in_flight_flows',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='last_event_table_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='last_hunt_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='last_interrogate_artifact_name',
            field=models.CharField(default='t', max_length=255),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='last_interrogate_flow_id',
            field=models.CharField(default='t', max_length=255),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='last_label_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='mac_addresses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='machine',
            field=models.CharField(default='t', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicesclient',
            name='client_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='devicesclient',
            name='status',
            field=models.CharField(default='Offline', max_length=20),
        ),
    ]
