# Generated by Django 5.1.1 on 2025-02-03 05:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0018_remove_devicesclient_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesclient',
            name='mac_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=17), default=list, size=None),
        ),
    ]
