# Generated by Django 5.1.1 on 2025-02-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0019_devicesclient_mac_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesclient',
            name='in_flight_flows',
        ),
        migrations.RemoveField(
            model_name='devicesclient',
            name='last_event_table_version',
        ),
        migrations.RemoveField(
            model_name='devicesclient',
            name='last_label_timestamp',
        ),
    ]
