# Generated by Django 5.1.1 on 2025-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0020_remove_devicesclient_in_flight_flows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesclient',
            name='first_seen_at',
            field=models.DateTimeField(default='2025-02-03 11:56:37+05'),
        ),
    ]
