# Generated by Django 5.1.1 on 2025-02-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0021_alter_devicesclient_first_seen_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryVQL',
        ),
    ]
