# Generated by Django 5.1.1 on 2024-10-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0005_alter_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
