# Generated by Django 5.1.1 on 2024-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0006_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=50)),
                ('release', models.CharField(max_length=50)),
                ('last_ip', models.CharField(max_length=50)),
                ('last_seen_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Devices',
            new_name='DeviceHost',
        ),
    ]
