# Generated by Django 5.1.1 on 2024-10-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0007_devicesclient_rename_devices_devicehost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehost',
            name='uptime',
        ),
    ]
