# Generated by Django 5.1.1 on 2024-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0008_remove_devicehost_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehost',
            name='status',
            field=models.CharField(default='Inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='devicesclient',
            name='status',
            field=models.CharField(default='Inactive', max_length=10),
        ),
    ]
