# Generated by Django 5.1.1 on 2024-11-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0010_devicehost_uptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehost',
            name='uptime',
        ),
    ]
