# Generated by Django 5.1.1 on 2025-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0022_delete_queryvql'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryVQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('query', models.TextField()),
            ],
        ),
    ]
