# Generated by Django 5.1.1 on 2025-02-17 06:14

from django.db import migrations
import json


def load_fixtures(apps, schema_editor):
    QueryVQL = apps.get_model('RControl', 'QueryVQL')

    fixture_path = 'RControl/fixtures/QueryVQL.json'
    with open(fixture_path, 'r') as f:
        data = json.load(f)

    for item in data:
        QueryVQL.objects.create(name=item['name'], query=item['query'])

def remove_fixtures(apps, schema_editor):
    QueryVQL = apps.get_model("your_app", "QueryVQL")
    QueryVQL.objects.filter(name__in=["get_clients_info", "get_server_info"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('RControl', '0023_queryvql'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, remove_fixtures)
    ]
