# Generated by Django 5.1.1 on 2025-02-13 10:19

from django.db import migrations


def load_artifacts(apps, schema_editor):
    QueryVQL = apps.get_model("Make_hunts", "QueryVQL")
    file_path = "Make_hunts/fixtures/artifacts.txt"

    artifact_name = None
    artifact_query = []

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        for line in lines:
            line = line.strip()
            if not line:
                continue

            if line.startswith("name:"):

                if artifact_name:
                    query_vql = "\n".join(artifact_query)
                    QueryVQL.objects.get_or_create(
                        name=artifact_name,
                        defaults={"query_vql": query_vql},
                    )


                artifact_name = line.split(":", 1)[1].strip()
                artifact_query = []

            else:
                artifact_query.append(line)


        if artifact_name:
            query_vql = "\n".join(artifact_query)
            QueryVQL.objects.get_or_create(
                name=artifact_name,
                defaults={"query_vql": query_vql},
            )

        print(f" Загружено артефактов из файла")
    except Exception as e:
        print(f"Ошибка загрузки артефактов: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('Make_hunts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_artifacts),
    ]
